language: nix
sudo: false
os:
- linux
#- osx

env:
  global:
  - CACHIX_CACHE=arc
  - HOSTNAMES="satorin shanghai"

git:
  submodules: false

install:
- git submodule update --init 'channels/*'
- nix-env -f channels/nixpkgs -iA nix
- cachix() { nix run -f run.nix cachix -c cachix "$@"; }
- |
  if [[ -n $CACHIX_CACHE ]]; then
    cachix use $CACHIX_CACHE
  fi

script:
- |
  (for host in $HOSTNAMES base personal desktop laptop; do
    echo BUILDING home-manager/$host &&
    ./nx home $host build || exit $?
  done)
- |
  (for host in $HOSTNAMES; do
    echo BUILDING nixos/$host &&
    ./nx switch $host build || exit $?
  done)
