substitutions:
  node_name: fornuftig-${id}
  friendly_name: FORNÜFTIG

packages:
  d1_mini: !include esp8266-d1-mini.yaml

sensor:
  - platform: adc
    pin: A0
    internal: true
    id: led_internal
    update_interval: 100ms
    accuracy_decimals: 1
    filters:
      - delta: 0.1
    on_value:
      if:
        condition:
          lambda: 'return x < 0.2;'
        then:
          - binary_sensor.template.publish:
              id: led_sensor
              state: OFF
        else:
          - binary_sensor.template.publish:
              id: led_sensor
              state: ON

binary_sensor:
  - platform: template
    id: led_sensor
    name: ${friendly_name} Filter
    device_class: problem
  - platform: gpio
    internal: true
    id: rotary_off
    pin:
      number: D7
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - fan.turn_off:
          id: fan_entity
  - platform: gpio
    internal: true
    id: rotary_low
    pin:
      number: D6
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - fan.turn_on:
          id: fan_entity
          speed: 1
  - platform: gpio
    internal: true
    id: rotary_med
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - fan.turn_on:
          id: fan_entity
          speed: 2
  - platform: gpio
    internal: true
    id: rotary_high
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - fan.turn_on:
          id: fan_entity
          speed: 3

output:
  - platform: gpio
    pin: D4
    id: out_high
    inverted: true
  - platform: gpio
    pin: D3
    id: out_med
    inverted: true
  - platform: gpio
    pin: D2
    id: out_low
    inverted: true
  - platform: template
    id: fan_speed
    type: float
    write_action:
    - if:
        condition:
          lambda: 'return state < 0.1;'
        then:
        - output.turn_off: out_low
        - output.turn_off: out_med
        - output.turn_off: out_high
    - if:
        condition:
          lambda: 'return state > 0.1 && state < 0.4;'
        then:
        - output.turn_on:  out_low
        - output.turn_off: out_med
        - output.turn_off: out_high
    - if:
        condition:
          lambda: 'return state > 0.4 && state < 0.7;'
        then:
        - output.turn_off: out_low
        - output.turn_on:  out_med
        - output.turn_off: out_high
    - if:
        condition:
          lambda: 'return state > 0.7;'
        then:
        - output.turn_off: out_low
        - output.turn_off: out_med
        - output.turn_on:  out_high

fan:
- platform: speed
  output: fan_speed
  id: fan_entity
  name: ${friendly_name} Fan
  speed_count: 3
