# https://community.home-assistant.io/t/ikea-fornuftig-in-home-assistant/318341

substitutions:
  node_name: fornuftig-${id}
  friendly_name: FÖRNUFTIG
  friendly_name_fan: $friendly_name
  gpio_rotary_off: D1
  gpio_rotary_low: D5
  gpio_rotary_med: D6
  gpio_rotary_high: D7
  gpio_out_high: D2
  gpio_out_med: D3
  gpio_out_low: D4

packages:
  d1_mini: !include esp8266-d1-mini.yaml

sensor:
  - platform: adc
    pin: A0
    internal: true
    id: led_internal
    update_interval: 100ms
    accuracy_decimals: 1
    filters:
      - delta: 0.1
    on_value:
      if:
        condition:
          lambda: 'return x < 0.2;'
        then:
          - binary_sensor.template.publish:
              id: led_sensor
              state: OFF
        else:
          - binary_sensor.template.publish:
              id: led_sensor
              state: ON
  - platform: template
    id: knob_position
    name: "Knob Position"
    #force_update: true

binary_sensor:
  - platform: template
    id: led_sensor
    name: $friendly_name Filter
    device_class: problem
  - platform: gpio
    internal: true
    id: rotary_off
    pin:
      number: $gpio_rotary_off
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - sensor.template.publish:
          id: knob_position
          state: 0
      - fan.turn_off:
          id: fan_entity
  - platform: gpio
    internal: true
    id: rotary_low
    pin:
      number: $gpio_rotary_low
      mode: INPUT_PULLUP
      inverted: True
    filters:
    # work around wiring issues and shorts in fornuftig-002
    - delayed_off: 100ms
    on_press:
      - sensor.template.publish:
          id: knob_position
          state: 1
      - fan.turn_on:
          id: fan_entity
          speed: 1
  - platform: gpio
    internal: true
    id: rotary_med
    pin:
      number: $gpio_rotary_med
      mode: INPUT_PULLUP
      inverted: True
    filters:
    - delayed_off: 100ms
    on_press:
      - sensor.template.publish:
          id: knob_position
          state: 2
      - fan.turn_on:
          id: fan_entity
          speed: 2
  - platform: gpio
    internal: true
    id: rotary_high
    pin:
      number: $gpio_rotary_high
      mode: INPUT_PULLUP
      inverted: true
    filters:
    - delayed_off: 100ms
    on_press:
      - sensor.template.publish:
          id: knob_position
          state: 3
      - fan.turn_on:
          id: fan_entity
          speed: 3

output:
  - platform: gpio
    pin: $gpio_out_high
    id: out_high
    inverted: true
  - platform: gpio
    pin: $gpio_out_med
    id: out_med
    inverted: true
  - platform: gpio
    pin: $gpio_out_low
    id: out_low
    inverted: true
  - platform: template
    id: fan_speed
    type: float
    write_action:
    - if:
        condition:
          lambda: 'return state < 0.1;'
        then:
        - output.turn_off: out_low
        - output.turn_off: out_med
        - output.turn_off: out_high
    - if:
        condition:
          lambda: 'return state > 0.1 && state < 0.4;'
        then:
        - output.turn_on:  out_low
        - output.turn_off: out_med
        - output.turn_off: out_high
    - if:
        condition:
          lambda: 'return state > 0.4 && state < 0.7;'
        then:
        - output.turn_off: out_low
        - output.turn_on:  out_med
        - output.turn_off: out_high
    - if:
        condition:
          lambda: 'return state > 0.7;'
        then:
        - output.turn_off: out_low
        - output.turn_off: out_med
        - output.turn_on:  out_high

fan:
- platform: speed
  output: fan_speed
  id: fan_entity
  name: $friendly_name_fan
  speed_count: 3
