substitutions:
  node_name: "kittylamp-${id}"
  friendly_name: "kittylamp-${id}"
  kittylamp_name: $friendly_name

packages:
  d1_mini: !include esp8266-d1-mini.yaml

e131:
  method: multicast
wled:

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812X
    pin: GPIO4
    num_leds: 7
    name: $kittylamp_name
    effects:
    - e131:
        universe: 1
        channels: RGB
    - wled:
        #port: 21324
    - random:
    - pulse:
    - flicker:
