substitutions:
  node_name: "led-${id}"
  friendly_name: "led-${id}"

packages:
  esp32_wroom32c4: !include esp32-wroom32-devkitc-v4.yaml

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800
