substitutions:
  node_name: outdoor-friend
  friendly_name: Outdoor

packages:
  d1_mini: !include esp8266-d1-mini.yaml
  dht22: !include dht22.yaml
  ccs811: !include ccs811.yaml
  i2c: !include esp8266-i2c.yaml
  uart: !include esp8266-uart.yaml

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: bedroom_display
    address: 0x3C
    contrast: 50%
