esphome:
  name: s31-$id

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

api:
  password: !secret api_password

ota:
  safe_mode: true
  password: !secret ota_password

time:
  - platform: homeassistant
    id: esptime

esp8266:
  board: esp01_1m
  restore_from_flash: true

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "S31-$id Button"
    on_press:
      - switch.toggle: s31_relay
  - platform: status
    name: "S31-$id WiFi Status"

sensor:
  - platform: wifi_signal
    name: "S31-$id WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "S31-$id Current"
      accuracy_decimals: 1
    voltage:
      name: "S31-$id Voltage"
      accuracy_decimals: 1
    power:
      name: "S31-$id Power"
      accuracy_decimals: 1
      id: s31_power
  - platform: total_daily_energy
    name: "S31-$id Daily Energy"
    power_id: s31_power

switch:
  - platform: gpio
    name: "S31-$id Relay"
    pin: GPIO12
    id: s31_relay
    restore_mode: RESTORE_DEFAULT_OFF

status_led:
  pin: GPIO13
