substitutions:
  node_name: "s31-${id}"
  friendly_name: "S31-${id}"

packages:
  esp01_1m: !include esp8266-esp01_1m.yaml

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: s31_relay

sensor:
  - platform: cse7766
    current:
      name: "${friendly_name} Current"
      accuracy_decimals: 1
    voltage:
      name: "${friendly_name} Voltage"
      accuracy_decimals: 1
    power:
      name: "${friendly_name} Power"
      accuracy_decimals: 1
      id: s31_power
  - platform: total_daily_energy
    name: "${friendly_name} Daily Energy"
    power_id: s31_power

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    pin: GPIO12
    id: s31_relay
    restore_mode: RESTORE_DEFAULT_OFF

status_led:
  pin: GPIO13
