sensor:
  - platform: scd4x
    measurement_mode: single_shot
    update_interval: 30s
    co2:
      name: "Bedroom CO2"
      id: scd41_co2
    temperature:
      name: "Bedroom Temperature 2"
      id: scd41_temp
    humidity:
      name: "Bedroom Humidity 2"
