packages:
  esp01_1m: !include esp8266-esp01_1m.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"

switch:
  - platform: gpio
    name: "${friendly_name} Relay 1"
    pin: GPIO12
    id: relay1
  - platform: gpio
    name: "${friendly_name} Relay 2"
    pin: GPIO14
    id: relay2
  - platform: gpio
    name: "${friendly_name} Relay 3"
    pin: GPIO15
    id: relay3
  - platform: gpio
    name: "${friendly_name} Relay 4"
    pin: GPIO5
    id: relay4

light:
  - platform: status_led
    name: "${friendly_name} LED"
    pin: GPIO0
