name: $(TeamProject).$(Build.DefinitionName).$(BuildID)$(Rev:.r)_$(SourceBranchName).$(Date:yyyyMMdd).$(Build.Reason)
resources:
  repositories:
  - repository: ci
    type: github
    name: arcnmx/ci
    ref: refs/heads/master
    endpoint: github/arcnmx/ci
variables:
  CI_ALLOW_ROOT: true
  CI_CLOSE_STDIN: true
  CACHIX_CACHE: arc
  TERM: linux
  HOSTNAMES: satorin shanghai
  imageLinux: ubuntu-latest
stages:
- stage: build
  displayName: Build
  jobs:
  - job: home
    displayName: Home
    timeoutInMinutes: 0
    pool:
      vmImage: ${{variables.imageLinux}}
    steps:
    - checkout: self
      submodules: false
    - bash: |
        set -eu

        gh_submodule() {
          # nixpkgs is too big and takes too long to download, so...
          SUBMODULE_COMMIT=$(git submodule status $1 | cut -d ' ' -f 1)
          curl -fSL https://github.com/$2/archive/${SUBMODULE_COMMIT#-}.tar.gz | tar -xz --strip-components=1 -C $1
        }

        git submodule update --init channels/{arc,home-manager,mozilla,nur}
        gh_submodule channels/nixpkgs nixos/nixpkgs
      displayName: git submodule init
    - template: azure/nix/install.yml@ci
      parameters:
        ciVersion: master
        config: config/ci.nix
    - bash: |
        (for host in $HOSTNAMES base personal desktop laptop; do
          echo BUILDING home-manager/$host &&
          ./nx home $host build --show-trace || exit $?
        done)
      displayName: build home
    - bash: |
        (for host in $HOSTNAMES; do
          echo BUILDING nixos/$host &&
          ./nx switch $host build || exit $?
        done)
      displayName: build nixos
