set encoding=utf-8
scriptencoding utf-8

runtime! plugin/sensible.vim

set viminfo='100000,<100000,s1000,h,n$XDG_DATA_HOME/vim/viminfo " Get rid of line copy limit

set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap//
set backupdir=$XDG_DATA_HOME/vim/backup
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set noerrorbells visualbell t_vb= " prevent bell on escape key presses

set tabstop=2
set softtabstop=2
set shiftwidth=2
set laststatus=1
set colorcolumn=100
set scrolloff=4
set linebreak showbreak=↪ " ↳
set list listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·
set nobackup
set showcmd
set relativenumber
set number
set cursorline
set shortmess+=I
set hlsearch
set completeopt=menuone,longest
set timeoutlen=100

set hidden " allow buffer switching without saving

syntax on
"set background=light " dark or light
set background=dark " dark or light

let g:netrw_home='$XDG_DATA_HOME/vim/netrw'
let g:EditorConfig_exclude_patterns = ['fugitive://.\*']

let g:rust_recommended_style=0
let g:rust_fold=1
"let g:rust_conceal=1 " neat but vim is buggy so can't use :(
let g:rust_conceal_mod_path=1
let g:rust_conceal_pub=1
let g:cargo_makeprg_params='check --color always'
au BufRead,BufNewFile *.rs compiler cargo

let g:vim_markdown_folding_disabled=1

au BufRead,BufNewFile *.kt setlocal filetype=kotlin
au BufRead,BufNewFile *.as setlocal filetype=javascript
au FileType notmuch-compose setlocal colorcolumn=78

xmap <M-C> y:call SendViaOSC52(getreg('"'))<cr>

nnoremap <esc><esc> :silent! nohls<cr>

" Don't use Ex mode, use Q for formatting
map Q gq
nnoremap q <Nop>

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif

if !exists(":Now")
  command Now call setline(line('.'), getline('.') . substitute(system('date -Iseconds'), '[\]\|[[:cntrl:]]', '', 'g'))
  cnoreabbrev <expr> now getcmdtype() !=# ':' ? 'now' : 'Now'
endif

command Spaces set expandtab
command Tabs set noexpandtab

" see https://github.com/vim/vim/issues/4365, no support for urxvt rgba: colours, nor T_CRC
if $TERM == "rxvt-unicode-256color"
  set t_RC= t_RB=
endif

set foldtext=MyFoldText()
function MyFoldText()
  let line = getline(v:foldstart)
  let sub = substitute(line, '/\*\|\*/\|{{{\d\=', '', 'g')
  return v:folddashes . sub
endfunction

" Avoid E173
if argc() > 1
  silent blast " load last buffer
  silent bfirst " switch back to the first
endif

" override the quit nag message
nnoremap <silent> <C-c> <nop>
