set noerrorbells visualbell t_vb= " prevent bell on escape key presses

set viminfo='100000,<100000,s1000,h " Get rid of line copy limit
if !has('nvim')
	set viminfo+=n$XDG_DATA_HOME/vim/viminfo
endif

set tabstop=2
set softtabstop=2
set shiftwidth=2
set laststatus=1
set colorcolumn=80,100,120
set scrolloff=4
set linebreak showbreak=↪ " ↳
set list listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·
set nobackup
set showcmd
set relativenumber
set number
set cursorline
set shortmess+=I
set hlsearch
set completeopt=menuone,longest
set noautoindent

set cmdheight=2 updatetime=300 shortmess+=c

set hidden " allow buffer switching without saving

syntax on
let g:EditorConfig_exclude_patterns = ['fugitive://.\*']

if $TERM ==# 'rxvt-unicode-256color' || has('vcon')
  set termguicolors
endif

let g:rust_recommended_style=0
let g:rust_fold=1
"let g:rust_conceal=1 " neat but vim is buggy so can't use :(
let g:rust_conceal_mod_path=1
let g:rust_conceal_pub=1
let g:cargo_makeprg_params='check --color always'
au BufRead,BufNewFile *.rs compiler cargo

let g:vim_markdown_folding_disabled=1

au BufRead,BufNewFile *.kt setlocal filetype=kotlin
au BufRead,BufNewFile *.as setlocal filetype=javascript

au FileType gitcommit setlocal colorcolumn=50,72

xmap <M-C> y:call SendViaOSC52(getreg('"'))<cr>

" Don't use Ex mode, use Q for formatting
map Q gq
nnoremap q <Nop>
vnoremap q <Esc>

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif

if !exists(":Now")
  command Now call setline(line('.'), getline('.') . substitute(system('date -Iseconds'), '[\]\|[[:cntrl:]]', '', 'g'))
  cnoreabbrev <expr> now getcmdtype() !=# ':' ? 'now' : 'Now'
endif

command Spaces set expandtab
command Tabs set noexpandtab

set foldtext=MyFoldText()
function MyFoldText()
  let line = getline(v:foldstart)
  let sub = substitute(line, '/\*\|\*/\|{{{\d\=', '', 'g')
  return v:folddashes . sub
endfunction

" override the quit nag message
nnoremap <silent> <C-c> <nop>
